
package fr.eseo.javaee.projet.visiteguidee.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Sat Mar 31 16:18:07 CEST 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "trouverVisiteResponse", namespace = "http://visiteguidee.projet.javaee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverVisiteResponse", namespace = "http://visiteguidee.projet.javaee.eseo.fr/")

public class TrouverVisiteResponse {

    @XmlElement(name = "return")
    private java.util.List<fr.eseo.javaee.projet.db.objet.Visite> _return;

    public java.util.List<fr.eseo.javaee.projet.db.objet.Visite> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<fr.eseo.javaee.projet.db.objet.Visite> new_return)  {
        this._return = new_return;
    }

}

