
package fr.eseo.javaee.projet.visiteguidee.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Mon Mar 26 15:12:17 CEST 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "trouverVisite", namespace = "http://visiteguidee.projet.javaee.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverVisite", namespace = "http://visiteguidee.projet.javaee.eseo.fr/")

public class TrouverVisite {

    @XmlElement(name = "arg0")
    private fr.eseo.javaee.projet.db.objet.Visite arg0;

    public fr.eseo.javaee.projet.db.objet.Visite getArg0() {
        return this.arg0;
    }

    public void setArg0(fr.eseo.javaee.projet.db.objet.Visite newArg0)  {
        this.arg0 = newArg0;
    }

}

